fos_user_profile_show:
    path: /profile/show
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'easyadmin'

fos_user_profile_index:
    path: /profile
    defaults:
        _controller:  Maximosojo\Bundle\BaseAdminBundle\Controller\FOSUserBundle\ProfileController::showAction
        _methods: GET

fos_user_profile_edit:
    path: /profile/edit
    defaults:
        _controller:  Maximosojo\Bundle\BaseAdminBundle\Controller\FOSUserBundle\ProfileController::editAction
        _methods: GET